version: '3.6'
services:
  illume:
    privileged: true
    container_name: illume
    image: illume
    build:
     context: .
     dockerfile: Dockerfile
    shm_size: 10gb
    volumes:
     - <TODO>:/workspace/repositories/ILLUME
     - <TODO>:/workspace/MAGMA
     - <TODO>:/workspace/datasets/COCO
    entrypoint: zsh
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    ports:
      - "<TODO>:8888"

